name: Build and Deploy to GitHub Pages

defaults:
  run:
    shell: bash

env:
  ACTIONS_STEP_DEBUG: true
  ACTIONS_UPLOAD_ARTIFACT: actions/upload-artifact@v4
  ACTIONS_DOWNLOAD_ARTIFACT: actions/download-artifact@v4

on:
  push:
    branches:
      - master
  # 允许手动触发工作流
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# 确保同一时间只有一个部署在运行
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Pages
        uses: actions/configure-pages@v5
        with:
          enablement: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm run build:prod

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./template

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
